"""
Catálogo oficial de los 193 países miembros de la Organización de las Naciones Unidas (ONU),
ordenados alfabéticamente en español, con sus respectivas banderas emoji.
"""

PAISES_ONU = [
    {"codigo": "AF", "nombre": "Afganistán", "flag": "🇦🇫"},
    {"codigo": "AL", "nombre": "Albania", "flag": "🇦🇱"},
    {"codigo": "DE", "nombre": "Alemania", "flag": "🇩🇪"},
    {"codigo": "AD", "nombre": "Andorra", "flag": "🇦🇩"},
    {"codigo": "AO", "nombre": "Angola", "flag": "🇦🇴"},
    {"codigo": "AG", "nombre": "Antigua y Barbuda", "flag": "🇦🇬"},
    {"codigo": "SA", "nombre": "Arabia Saudita", "flag": "🇸🇦"},
    {"codigo": "DZ", "nombre": "Argelia", "flag": "🇩🇿"},
    {"codigo": "AR", "nombre": "Argentina", "flag": "🇦🇷"},
    {"codigo": "AM", "nombre": "Armenia", "flag": "🇦🇲"},
    {"codigo": "AU", "nombre": "Australia", "flag": "🇦🇺"},
    {"codigo": "AT", "nombre": "Austria", "flag": "🇦🇹"},
    {"codigo": "AZ", "nombre": "Azerbaiyán", "flag": "🇦🇿"},
    {"codigo": "BS", "nombre": "Bahamas", "flag": "🇧🇸"},
    {"codigo": "BD", "nombre": "Bangladés", "flag": "🇧🇩"},
    {"codigo": "BB", "nombre": "Barbados", "flag": "🇧🇧"},
    {"codigo": "BH", "nombre": "Baréin", "flag": "🇧🇭"},
    {"codigo": "BE", "nombre": "Bélgica", "flag": "🇧🇪"},
    {"codigo": "BZ", "nombre": "Belice", "flag": "🇧🇿"},
    {"codigo": "BJ", "nombre": "Benín", "flag": "🇧🇯"},
    {"codigo": "BY", "nombre": "Bielorrusia", "flag": "🇧🇾"},
    {"codigo": "MM", "nombre": "Birmania (Myanmar)", "flag": "🇲🇲"},
    {"codigo": "BO", "nombre": "Bolivia", "flag": "🇧🇴"},
    {"codigo": "BA", "nombre": "Bosnia y Herzegovina", "flag": "🇧🇦"},
    {"codigo": "BW", "nombre": "Botsuana", "flag": "🇧🇼"},
    {"codigo": "BR", "nombre": "Brasil", "flag": "🇧🇷"},
    {"codigo": "BN", "nombre": "Brunéi", "flag": "🇧🇳"},
    {"codigo": "BG", "nombre": "Bulgaria", "flag": "🇧🇬"},
    {"codigo": "BF", "nombre": "Burkina Faso", "flag": "🇧🇫"},
    {"codigo": "BI", "nombre": "Burundi", "flag": "🇧🇮"},
    {"codigo": "BT", "nombre": "Bután", "flag": "🇧🇹"},
    {"codigo": "CV", "nombre": "Cabo Verde", "flag": "🇨🇻"},
    {"codigo": "KH", "nombre": "Camboya", "flag": "🇰🇭"},
    {"codigo": "CM", "nombre": "Camerún", "flag": "🇨🇲"},
    {"codigo": "CA", "nombre": "Canadá", "flag": "🇨🇦"},
    {"codigo": "QA", "nombre": "Catar", "flag": "🇶🇦"},
    {"codigo": "TD", "nombre": "Chad", "flag": "🇹🇩"},
    {"codigo": "CL", "nombre": "Chile", "flag": "🇨🇱"},
    {"codigo": "CN", "nombre": "China", "flag": "🇨🇳"},
    {"codigo": "CY", "nombre": "Chipre", "flag": "🇨🇾"},
    {"codigo": "CO", "nombre": "Colombia", "flag": "🇨🇴"},
    {"codigo": "KM", "nombre": "Comoras", "flag": "🇰🇲"},
    {"codigo": "CG", "nombre": "Congo", "flag": "🇨🇬"},
    {"codigo": "KP", "nombre": "Corea del Norte", "flag": "🇰🇵"},
    {"codigo": "KR", "nombre": "Corea del Sur", "flag": "🇰🇷"},
    {"codigo": "CI", "nombre": "Costa de Marfil", "flag": "🇨🇮"},
    {"codigo": "CR", "nombre": "Costa Rica", "flag": "🇨🇷"},
    {"codigo": "HR", "nombre": "Croacia", "flag": "🇭🇷"},
    {"codigo": "CU", "nombre": "Cuba", "flag": "🇨🇺"},
    {"codigo": "DK", "nombre": "Dinamarca", "flag": "🇩🇰"},
    {"codigo": "DM", "nombre": "Dominica", "flag": "🇩🇲"},
    {"codigo": "EC", "nombre": "Ecuador", "flag": "🇪🇨"},
    {"codigo": "EG", "nombre": "Egipto", "flag": "🇪🇬"},
    {"codigo": "SV", "nombre": "El Salvador", "flag": "🇸🇻"},
    {"codigo": "AE", "nombre": "Emiratos Árabes Unidos", "flag": "🇦🇪"},
    {"codigo": "ER", "nombre": "Eritrea", "flag": "🇪🇷"},
    {"codigo": "SK", "nombre": "Eslovaquia", "flag": "🇸🇰"},
    {"codigo": "SI", "nombre": "Eslovenia", "flag": "🇸🇮"},
    {"codigo": "ES", "nombre": "España", "flag": "🇪🇸"},
    {"codigo": "US", "nombre": "Estados Unidos", "flag": "🇺🇸"},
    {"codigo": "EE", "nombre": "Estonia", "flag": "🇪🇪"},
    {"codigo": "ET", "nombre": "Etiopía", "flag": "🇪🇹"},
    {"codigo": "PH", "nombre": "Filipinas", "flag": "🇵🇭"},
    {"codigo": "FI", "nombre": "Finlandia", "flag": "🇫🇮"},
    {"codigo": "FJ", "nombre": "Fiyi", "flag": "🇫🇯"},
    {"codigo": "FR", "nombre": "Francia", "flag": "🇫🇷"},
    {"codigo": "GA", "nombre": "Gabón", "flag": "🇬🇦"},
    {"codigo": "GM", "nombre": "Gambia", "flag": "🇬🇲"},
    {"codigo": "GE", "nombre": "Georgia", "flag": "🇬🇪"},
    {"codigo": "GH", "nombre": "Ghana", "flag": "🇬🇭"},
    {"codigo": "GD", "nombre": "Granada", "flag": "🇬🇩"},
    {"codigo": "GR", "nombre": "Grecia", "flag": "🇬🇷"},
    {"codigo": "GT", "nombre": "Guatemala", "flag": "🇬🇹"},
    {"codigo": "GN", "nombre": "Guinea", "flag": "🇬🇳"},
    {"codigo": "GW", "nombre": "Guinea-Bisáu", "flag": "🇬🇼"},
    {"codigo": "GQ", "nombre": "Guinea Ecuatorial", "flag": "🇬🇶"},
    {"codigo": "GY", "nombre": "Guyana", "flag": "🇬🇾"},
    {"codigo": "HT", "nombre": "Haití", "flag": "🇭🇹"},
    {"codigo": "HN", "nombre": "Honduras", "flag": "🇭🇳"},
    {"codigo": "HU", "nombre": "Hungría", "flag": "🇭🇺"},
    {"codigo": "IN", "nombre": "India", "flag": "🇮🇳"},
    {"codigo": "ID", "nombre": "Indonesia", "flag": "🇮🇩"},
    {"codigo": "IQ", "nombre": "Irak", "flag": "🇮🇶"},
    {"codigo": "IR", "nombre": "Irán", "flag": "🇮🇷"},
    {"codigo": "IE", "nombre": "Irlanda", "flag": "🇮🇪"},
    {"codigo": "IS", "nombre": "Islandia", "flag": "🇮🇸"},
    {"codigo": "MH", "nombre": "Islas Marshall", "flag": "🇲🇭"},
    {"codigo": "SB", "nombre": "Islas Salomón", "flag": "🇸🇧"},
    {"codigo": "IL", "nombre": "Israel", "flag": "🇮🇱"},
    {"codigo": "IT", "nombre": "Italia", "flag": "🇮🇹"},
    {"codigo": "JM", "nombre": "Jamaica", "flag": "🇯🇲"},
    {"codigo": "JP", "nombre": "Japón", "flag": "🇯🇵"},
    {"codigo": "JO", "nombre": "Jordania", "flag": "🇯🇴"},
    {"codigo": "KZ", "nombre": "Kazajistán", "flag": "🇰🇿"},
    {"codigo": "KE", "nombre": "Kenia", "flag": "🇰🇪"},
    {"codigo": "KG", "nombre": "Kirguistán", "flag": "🇰🇬"},
    {"codigo": "KI", "nombre": "Kiribati", "flag": "🇰🇮"},
    {"codigo": "KW", "nombre": "Kuwait", "flag": "🇰🇼"},
    {"codigo": "LA", "nombre": "Laos", "flag": "🇱🇦"},
    {"codigo": "LS", "nombre": "Lesoto", "flag": "🇱🇸"},
    {"codigo": "LV", "nombre": "Letonia", "flag": "🇱🇻"},
    {"codigo": "LB", "nombre": "Líbano", "flag": "🇱🇧"},
    {"codigo": "LR", "nombre": "Liberia", "flag": "🇱🇷"},
    {"codigo": "LY", "nombre": "Libia", "flag": "🇱🇾"},
    {"codigo": "LI", "nombre": "Liechtenstein", "flag": "🇱🇮"},
    {"codigo": "LT", "nombre": "Lituania", "flag": "🇱🇹"},
    {"codigo": "LU", "nombre": "Luxemburgo", "flag": "🇱🇺"},
    {"codigo": "MK", "nombre": "Macedonia del Norte", "flag": "🇲🇰"},
    {"codigo": "MG", "nombre": "Madagascar", "flag": "🇲🇬"},
    {"codigo": "MY", "nombre": "Malasia", "flag": "🇲🇾"},
    {"codigo": "MW", "nombre": "Malaui", "flag": "🇲🇼"},
    {"codigo": "MV", "nombre": "Maldivas", "flag": "🇲🇻"},
    {"codigo": "ML", "nombre": "Malí", "flag": "🇲🇱"},
    {"codigo": "MT", "nombre": "Malta", "flag": "🇲🇹"},
    {"codigo": "MA", "nombre": "Marruecos", "flag": "🇲🇦"},
    {"codigo": "MU", "nombre": "Mauricio", "flag": "🇲🇺"},
    {"codigo": "MR", "nombre": "Mauritania", "flag": "🇲🇷"},
    {"codigo": "MX", "nombre": "México", "flag": "🇲🇽"},
    {"codigo": "FM", "nombre": "Micronesia", "flag": "🇫🇲"},
    {"codigo": "MD", "nombre": "Moldavia", "flag": "🇲🇩"},
    {"codigo": "MC", "nombre": "Mónaco", "flag": "🇲🇨"},
    {"codigo": "MN", "nombre": "Mongolia", "flag": "🇲🇳"},
    {"codigo": "ME", "nombre": "Montenegro", "flag": "🇲🇪"},
    {"codigo": "MZ", "nombre": "Mozambique", "flag": "🇲🇿"},
    {"codigo": "NA", "nombre": "Namibia", "flag": "🇳🇦"},
    {"codigo": "NR", "nombre": "Nauru", "flag": "🇳🇷"},
    {"codigo": "NP", "nombre": "Nepal", "flag": "🇳🇵"},
    {"codigo": "NI", "nombre": "Nicaragua", "flag": "🇳🇮"},
    {"codigo": "NE", "nombre": "Níger", "flag": "🇳🇪"},
    {"codigo": "NG", "nombre": "Nigeria", "flag": "🇳🇬"},
    {"codigo": "NO", "nombre": "Noruega", "flag": "🇳🇴"},
    {"codigo": "NZ", "nombre": "Nueva Zelanda", "flag": "🇳🇿"},
    {"codigo": "OM", "nombre": "Omán", "flag": "🇴🇲"},
    {"codigo": "NL", "nombre": "Países Bajos", "flag": "🇳🇱"},
    {"codigo": "PK", "nombre": "Pakistán", "flag": "🇵🇰"},
    {"codigo": "PW", "nombre": "Palaos", "flag": "🇵🇼"},
    {"codigo": "PA", "nombre": "Panamá", "flag": "🇵🇦"},
    {"codigo": "PG", "nombre": "Papúa Nueva Guinea", "flag": "🇵🇬"},
    {"codigo": "PY", "nombre": "Paraguay", "flag": "🇵🇾"},
    {"codigo": "PE", "nombre": "Perú", "flag": "🇵🇪"},
    {"codigo": "PL", "nombre": "Polonia", "flag": "🇵🇱"},
    {"codigo": "PT", "nombre": "Portugal", "flag": "🇵🇹"},
    {"codigo": "GB", "nombre": "Reino Unido", "flag": "🇬🇧"},
    {"codigo": "CF", "nombre": "República Centroafricana", "flag": "🇨🇫"},
    {"codigo": "CZ", "nombre": "República Checa", "flag": "🇨🇿"},
    {"codigo": "DO", "nombre": "República Dominicana", "flag": "🇩🇴"},
    {"codigo": "RW", "nombre": "Ruanda", "flag": "🇷🇼"},
    {"codigo": "RO", "nombre": "Rumania", "flag": "🇷🇴"},
    {"codigo": "RU", "nombre": "Rusia", "flag": "🇷🇺"},
    {"codigo": "WS", "nombre": "Samoa", "flag": "🇼🇸"},
    {"codigo": "KN", "nombre": "San Cristóbal y Nieves", "flag": "🇰🇳"},
    {"codigo": "SM", "nombre": "San Marino", "flag": "🇸🇲"},
    {"codigo": "VC", "nombre": "San Vicente y las Granadinas", "flag": "🇻🇨"},
    {"codigo": "LC", "nombre": "Santa Lucía", "flag": "🇱🇨"},
    {"codigo": "ST", "nombre": "Santo Tomé y Príncipe", "flag": "🇸🇹"},
    {"codigo": "SN", "nombre": "Senegal", "flag": "🇸🇳"},
    {"codigo": "RS", "nombre": "Serbia", "flag": "🇷🇸"},
    {"codigo": "SC", "nombre": "Seychelles", "flag": "🇸🇨"},
    {"codigo": "SL", "nombre": "Sierra Leona", "flag": "🇸🇱"},
    {"codigo": "SG", "nombre": "Singapur", "flag": "🇸🇬"},
    {"codigo": "SY", "nombre": "Siria", "flag": "🇸🇾"},
    {"codigo": "SO", "nombre": "Somalia", "flag": "🇸🇴"},
    {"codigo": "LK", "nombre": "Sri Lanka", "flag": "🇱🇰"},
    {"codigo": "SZ", "nombre": "Esuatini (Suazilandia)", "flag": "🇸🇿"},
    {"codigo": "ZA", "nombre": "Sudáfrica", "flag": "🇿🇦"},
    {"codigo": "SD", "nombre": "Sudán", "flag": "🇸🇩"},
    {"codigo": "SS", "nombre": "Sudán del Sur", "flag": "🇸🇸"},
    {"codigo": "SE", "nombre": "Suecia", "flag": "🇸🇪"},
    {"codigo": "CH", "nombre": "Suiza", "flag": "🇨🇭"},
    {"codigo": "SR", "nombre": "Surinam", "flag": "🇸🇷"},
    {"codigo": "TH", "nombre": "Tailandia", "flag": "🇹🇭"},
    {"codigo": "TZ", "nombre": "Tanzania", "flag": "🇹🇿"},
    {"codigo": "TJ", "nombre": "Tayikistán", "flag": "🇹🇯"},
    {"codigo": "TL", "nombre": "Timor Oriental", "flag": "🇹🇱"},
    {"codigo": "TG", "nombre": "Togo", "flag": "🇹🇬"},
    {"codigo": "TO", "nombre": "Tonga", "flag": "🇹🇴"},
    {"codigo": "TT", "nombre": "Trinidad y Tobago", "flag": "🇹🇹"},
    {"codigo": "TN", "nombre": "Túnez", "flag": "🇹🇳"},
    {"codigo": "TM", "nombre": "Turkmenistán", "flag": "🇹🇲"},
    {"codigo": "TR", "nombre": "Turquía", "flag": "🇹🇷"},
    {"codigo": "TV", "nombre": "Tuvalu", "flag": "🇹🇻"},
    {"codigo": "UA", "nombre": "Ucrania", "flag": "🇺🇦"},
    {"codigo": "UG", "nombre": "Uganda", "flag": "🇺🇬"},
    {"codigo": "UY", "nombre": "Uruguay", "flag": "🇺🇾"},
    {"codigo": "UZ", "nombre": "Uzbekistán", "flag": "🇺🇿"},
    {"codigo": "VU", "nombre": "Vanuatu", "flag": "🇻🇺"},
    {"codigo": "VE", "nombre": "Venezuela", "flag": "🇻🇪"},
    {"codigo": "VN", "nombre": "Vietnam", "flag": "🇻🇳"},
    {"codigo": "YE", "nombre": "Yemen", "flag": "🇾🇪"},
    {"codigo": "DJ", "nombre": "Yibuti", "flag": "🇩🇯"},
    {"codigo": "ZM", "nombre": "Zambia", "flag": "🇿🇲"},
    {"codigo": "ZW", "nombre": "Zimbabue", "flag": "🇿🇼"},
]

TIPOS_PERMISO_RESIDENCIA = [
    "Ciudadano Nivel Nativo",
    "Residente Permanente",
    "Visa de Trabajo / Empleo",
    "Visa de Inversionista / Negocios",
    "Visa de Estudiante",
    "Permiso Temporal de Protección / Asilo",
    "Visa de Nómada Digital",
    "Otro",
]

CIUDADES_POPULARES = [
    "Madrid, España",
    "Barcelona, España",
    "Valencia, España",
    "Sevilla, España",
    "Miami, Estados Unidos",
    "Nueva York, Estados Unidos",
    "Orlando, Estados Unidos",
    "Houston, Estados Unidos",
    "Los Ángeles, Estados Unidos",
    "Toronto, Canadá",
    "Montreal, Canadá",
    "Vancouver, Canadá",
    "Londres, Reino Unido",
    "París, Francia",
    "Múnich, Alemania",
    "Berlín, Alemania",
    "Sídney, Australia",
    "Melbourne, Australia",
    "Santiago, Chile",
    "Ciudad de México, México",
    "Panamá, Panamá",
    "Quito, Ecuador",
    "Guayaquil, Ecuador",
    "Lima, Perú",
    "Bogotá, Colombia",
    "Medellín, Colombia",
    "Cali, Colombia",
    "Barranquilla, Colombia",
    "Bucaramanga, Colombia",
    "Cartagena, Colombia",
    "Pereira, Colombia",
    "Manizales, Colombia",
    "Cúcuta, Colombia",
]

