"""
Mapeo automático UPZ pre-2023 (116) → UPL post-2023 (33).
Generado por scripts/generar_mapeo_upz_upl.py
"""

# Clave: nombre UPZ pre-2023 en MAYÚSCULAS (como aparece en el H3 maestro)
# Valor: nombre UPL post-2023 (como aparece en el formulario de búsqueda)
UPZ_A_UPL: dict[str, str] = {
    '20 DE JULIO': 'San Cristóbal',
    'AEROPUERTO EL DORADO': 'Fontibón',
    'ALAMOS': 'Salitre',
    'ALFONSO LOPEZ': 'Usme - Entrenubes',
    'AMERICAS': 'Kennedy',
    'APOGEO': 'Bosa',
    'ARBORIZADORA': 'Arborizadora',
    'BAVARIA': 'Tintal',
    'BOLIVIA': 'Engativá',
    'BOSA CENTRAL': 'Bosa',
    'BOSA OCCIDENTAL': 'Edén',
    'BOYACA REAL': 'Tabora',
    'BRITALIA': 'Britalia',
    'CALANDAIMA': 'Tintal',
    'CAPELLANIA': 'Salitre',
    'CARVAJAL': 'Kennedy',
    'CASA BLANCA SUBA': 'Britalia',
    'CASTILLA': 'Tintal',
    'CHAPINERO': 'Chapinero',
    'CHICO LAGO': 'Chapinero',
    'CIUDAD JARDIN': 'Restrepo',
    'CIUDAD MONTES': 'Puente Aranda',
    'CIUDAD SALITRE OCCIDENTAL': 'Salitre',
    'CIUDAD SALITRE ORIENTAL': 'Teusaquillo',
    'CIUDAD USME': 'Usme - Entrenubes',
    'COMUNEROS': 'Usme - Entrenubes',
    'CORABASTOS': 'Patio Bonito',
    'COUNTRY CLUB': 'Usaquén',
    'DANUBIO': 'Rafael Uribe',
    'DIANA TURBAY': 'Rafael Uribe',
    'DOCE DE OCTUBRE': 'Barrios Unidos',
    'EL MOCHUELO': 'Lucero',
    'EL PORVENIR': 'Porvenir',
    'EL PRADO': 'Niza',
    'EL REFUGIO': 'Chapinero',
    'EL RINCON': 'Rincón de Suba',
    'EL TESORO': 'Lucero',
    'ENGATIVA': 'Engativá',
    'FONTIBON': 'Fontibón',
    'FONTIBON SAN PABLO': 'Fontibón',
    'GALERIAS': 'Teusaquillo',
    'GARCES NAVAS': 'Engativá',
    'GRAN BRITALIA': 'Edén',
    'GRAN YOMASA': 'Rafael Uribe',
    'GRANJAS DE TECHO': 'Salitre',
    'GUAYMARAL': 'Torca',
    'ISMAEL PERDOMO': 'Arborizadora',
    'JARDIN BOTANICO': 'Salitre',
    'JERUSALEM': 'Arborizadora',
    'KENNEDY CENTRAL': 'Kennedy',
    'LA ACADEMIA': 'Torca',
    'LA ALHAMBRA': 'Niza',
    'LA CANDELARIA': 'Centro Histórico',
    'LA ESMERALDA': 'Teusaquillo',
    'LA FLORA': 'Usme - Entrenubes',
    'LA FLORESTA': 'Niza',
    'LA GLORIA': 'San Cristóbal',
    'LA MACARENA': 'Centro Histórico',
    'LA SABANA': 'Centro Histórico',
    'LA URIBE': 'Toberín',
    'LAS CRUCES': 'Centro Histórico',
    'LAS FERIAS': 'Tabora',
    'LAS MARGARITAS': 'Porvenir',
    'LAS NIEVES': 'Centro Histórico',
    'LOS ALCAZARES': 'Barrios Unidos',
    'LOS ANDES': 'Barrios Unidos',
    'LOS CEDROS': 'Usaquén',
    'LOS LIBERTADORES': 'Usme - Entrenubes',
    'LOURDES': 'Centro Histórico',
    'LUCERO': 'Lucero',
    'MARCO FIDEL SUAREZ': 'Rafael Uribe',
    'MARRUECOS': 'Rafael Uribe',
    'MINUTO DE DIOS': 'Tabora',
    'MODELIA': 'Salitre',
    'MONTE BLANCO': 'Cuenca del Tunjuelo',
    'MUZU': 'Puente Aranda',
    'NIZA': 'Niza',
    'PARDO RUBIO': 'Cerros Orientales',
    'PARQUE ENTRENUBES': 'Rafael Uribe',
    'PARQUE SALITRE': 'Barrios Unidos',
    'PARQUE SIMON BOLIVAR - CAN': 'Teusaquillo',
    'PASEO DE LOS LIBERTADORES': 'Torca',
    'PATIO BONITO': 'Patio Bonito',
    'PUENTE ARANDA': 'Puente Aranda',
    'QUINTA PAREDES': 'Teusaquillo',
    'QUIROGA': 'Restrepo',
    'RESTREPO': 'Restrepo',
    'SAGRADO CORAZON': 'Centro Histórico',
    'SAN BLAS': 'San Cristóbal',
    'SAN CRISTOBAL NORTE': 'Toberín',
    'SAN FRANCISCO': 'Arborizadora',
    'SAN ISIDRO - PATIOS': 'Cerros Orientales',
    'SAN JOSE': 'Restrepo',
    'SAN JOSE DE BAVARIA': 'Britalia',
    'SAN RAFAEL': 'Puente Aranda',
    'SANTA BARBARA': 'Usaquén',
    'SANTA CECILIA': 'Salitre',
    'SANTA ISABEL': 'Centro Histórico',
    'SOSIEGO': 'San Cristóbal',
    'SUBA': 'Suba',
    'TEUSAQUILLO': 'Teusaquillo',
    'TIBABUYES': 'Tibabuyes',
    'TIMIZA': 'Bosa',
    'TINTAL NORTE': 'Tintal',
    'TINTAL SUR': 'Porvenir',
    'TOBERIN': 'Toberín',
    'TUNJUELITO': 'Tunjuelito',
    'UPR RÍO BLANCO': 'Sumapáz',
    'UPR RÍO SUMAPAZ': 'Sumapáz',
    'UPR RÍO TUNJUELO': 'Cuenca del Tunjuelo',
    'UPR ZONA NORTE': 'Torca',
    'USAQUEN': 'Usaquén',
    'VENECIA': 'Tunjuelito',
    'VERBENAL': 'Toberín',
    'ZONA FRANCA': 'Fontibón',
    'ZONA INDUSTRIAL': 'Puente Aranda',
}
